# -*- coding: utf-8 -*-
"""Untitled48.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13lpGJ1yMDOXi7NSu2d-tR8GQbdlP5_og
"""

class Phone:
  category = "Electronics"

  # constructor
  def __init__(self,model,camera,battery):
    self.model = model
    self.camera = camera
    self.battery = battery

apple = Phone("iphn-14",3200,48)
print(apple.model)

"""# Inheritence"""

class Student:
  def __init__(self,name,age):
    self.name = name
    self.age = age

  def introduce(self):
    print(f"My name is {self.name} and my age is {self.age}")


class Student1(Student):

  def study(self):
    print(f"{self.name} is studying")



Teacher = Student1("Prethul", 22)

Teacher.introduce()
Teacher.study()

# parent class
class Person:

  def __init__(self,name,age):
    self.name = name
    self.age = age

  # person class ar method
  def introduce(self):
    print(f"My Name is {self.name}")
    print(f"My Age is {self.age}")

#child class
class Student(Person):
  def __init__(self, name, age,student_id,department):
     super().__init__(name, age)
     self.student_id = student_id
     self.department = department

  def show_department_info(self):
    print(f"Hello i am {self.name} and my Student ID is {self.student_id}")
    print(f"I am from {self.department} Department")


class GraduateStudent(Student):

  def __init__(self,name, age, student_id,department,thesis_topic):
    super().__init__(name,age,student_id,department)

    self.thesis_topic = thesis_topic


  def topic(self):
    print(f"My Thesis Topic is {self.thesis_topic}")


obj = GraduateStudent(
    "Dipto Howlader Prethul",
    22,
    22330810,
    "CSE",
    "AI Powered Brain tumor Detection"
)

obj.introduce()
obj.show_department_info()
obj.topic()

class Phone:
  # method
  def apple(self):
    print("i am a student")

class Iphon(Phone):
  #method
  def apple(self):
    print("i am going to school")

p = Phone()
i = Iphon()

p.apple()
i.apple()

x = int(input("Enter first number : "))
y = int(input("Enter second number :"))

sum = x + y
sub = x - y
mul = x * y
div = x / y
mod = x % y


print(f"Sum : {sum}")
print(f"Sub : {sub}")
print(f"Mul : {mul}")
print(f"Div : {div}")
print(f"Mod : {mod}")

